### ISSUE TITLE
VGG-FCN  t7 file

### ISSUE THREAD

**Issue by YuanEZhou** [JonghwanMun/TextguidedATT#6]
You had released the Res-101.t7 file to extract image features, can you release the VGG-FCN  t7 file ? Thanks.

**Comment by JonghwanMun** [comment]
When I implemented FCN-based text-guided attention model, I use the pre-trained caffe model from [From Captions to Visual Concepts and Back](https://github.com/s-gupta/visual-concepts).
But, currently the FCN-model and corresponding feature extraction code are missing. 
Sorry for that, but I think it is simple to load pre-trained caffe model in torch with [loadcaffe package](https://github.com/szagoruyko/loadcaffe) and you can easily write code.

**Comment by YuanEZhou** [comment]
Thanks!

**Comment by YuanEZhou** [comment]
I follow your advice and  downlaod the snapsshot_iter240000.caffemodel from  corresponding address, but there is not 'deploy.prototxt' file .  Do you modify the original  VGG-16 prototxt file by replacing the (fc6, fc7,fc8) with fully convolutional network ?   What the dimentions of extracted feature maps  given 512*512 images ?

**Comment by JonghwanMun** [comment]
The "deploy.prototxt" file is on "visual-concepts/output/vgg" folder in
prototxt <https://github.com/s-gupta/visual-concepts/tree/master/output/vgg>
.
I also extracted features at the layer named by "fc-conv7" (or "relu7") and
the size of feature maps was 10x10.

If you have other questions, feel free to ask me :)

2018-01-03 16:53 GMT+09:00 YE Zhou <notifications@github.com>:

**Comment by YuanEZhou** [comment]
Thank you! I found the deploy.prototxt file.  But I still have some confusion as follow:
If you extract features at the layer named by "fc-conv7" (or "relu7") and the size of feature maps was 10* 10* 4096. The dimention of feature maps is so big! Why not  extract features at the layer name by "fc8_coco" ?

**Comment by JonghwanMun** [comment]
The output of "fc8_coco" layer is probability for attributes, thus I use
the visual features from "fc-conv7" as we usually obtain features from fc7
layer rather than fc8 layer in VGG-net.
Also, note that the outputs of ResNet are 14x14x2048 size of features given
448x448 images.

2018-01-04 14:17 GMT+09:00 YE Zhou <notifications@github.com>:

**Comment by YuanEZhou** [comment]
Thank you very much!
